[package]
name = "cosmic-workspaces"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
calloop = { version = "0.13.0", features = ["executor"] }
clap = { version = "4", features = ["derive"] }
cosmic-comp-config = { git = "https://github.com/pop-os/cosmic-comp" }
env_logger = "0.11.0"
futures-channel = "0.3.25"
gbm = "0.14.0"
libcosmic = { git = "https://github.com/pop-os/libcosmic", default-features = false, features = ["tokio", "wayland", "single-instance"] }
cosmic-config = { git = "https://github.com/pop-os/libcosmic" }
freedesktop-desktop-entry = "0.5.0"
freedesktop-icons = "0.2.4"

memmap2 = "0.9.0"
tokio = "1.23.0"
wayland-protocols = "0.31.0"
zbus = { version = "4.0.0", default-features = false, features = ["tokio"] }
once_cell = "1.18.0"
delegate = "0.12.0"
itertools = "0.12.0"
log = "0.4.20"
i18n-embed-fl = "0.8.0"
rust-embed = "8.1.0"
rustix = { version = "0.38.30", features  = ["fs"] }
calloop-wayland-source = "0.3.0"

[dependencies.i18n-embed]
version = "0.14.1"
features = ["fluent-system", "desktop-requester"]

[features]
default = ["wgpu"]
wgpu = ["libcosmic/wgpu"]
# Debugging features
force-shm-screencopy = []
no-subsurfaces = ["force-shm-screencopy"]

[profile.dev]
# Not usable at opt-level 0, at least with software renderer
opt-level = 1

# [patch."https://github.com/pop-os/libcosmic"]
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
